triggers = ["$quote", "$quotes"]

[quotes]
loli = "\"C'est parce que c'est pas du loli rape\" - kiniamaro 2014"
mac = "\"ouais, I'm not letting it die, c'est mon dernier mac à vie\" - alxgnon 2014"
arch = "\"Check ben comment j'installe Arch en 30 minutes!\" - MrJudgemental 2014"
biblio = "\"En arrière de la biblio municipale\" - SBSTP 2014"
broken = "\"The bot is broken!\" - everyone 2014"
rodric = "http://i.imgur.com/0CW6W7t.jpg"
lookingformaniac = "http://pastebin.com/BrtTPvXT"
nonsense = "\"tu me faire un debian pi un avec un pingouin du si vx\" - SBSTP 2014"
irc = "\"ça me tente pas d'attendre sur l'irc\" - DrFoliberg 2014"
grab = "\"moi j'aime bien grab des petites filles defois\" - alxgnon 2014"
java = "\"laissez moi faire du java criss\" - DrFoliberg 2014"
drugs = "\"Alright I taking drugs\" - Maro-kun 2015"
16 = "\"non fadrait que seize ans messemble c'est faisable\" - Maro-kun 2015"
cul = "\"Entk, moi j'aime juste les culs de gars.\" - petitprince 2015"
lesbien = "\"I NEVER NEVER WAS A lesbien\" - Maro-Kun 2015"
"<3 java" = "\"<3 java\" - maxdup 2015"
"privé" = "\"comment tu as eu ca?? c'est tres privé !!!!\" - danou_ 2015"
snake = "\"Dude, I'd fuck that snake raw\" - FifteenIsForShow 2015"
dog = "\"Why am I a dog\" - alxgnon 2015"
"now you do" = "\"hey guys, do i have a quote yet?\" - Potato-Sama 2015"
"dragon dildo" = "\"Hah, I wish I had one!\" - FifteenIsForShow 2015"
"anally raped" = "\"if I'm to be anally raped, I'd rather it be dry and get the full experience\" - alxgnon 2015"
"first mac" = "\"je regrette de pas avoir un mac\" - FifteenIsForShow 2015"
boxer = "\"la shape de la dick dans le boxer, ça c'est hot\" - Kiniamaro 2015"
chimique = "\"Mon pénis est chimique\" - alxgnon 2015"
"15's life" = "\"Now's the time to question what I'm doing with my life\" - FifteenIsTooShor 2016"
spanking = "\"spanking is not abusive\" - alxgnon 2016"
heaven = "\"in fact my picture of heaven is just me inserting into a warm wet hole over and over again forever\" - alxgnon 2016"
weeds = "\"I want to sex now with some weeds oh fuck\" - abd31999 2017"
"finish off" = "\"alxgnon, see if you can get yourself to finish Off!\" - Fifteen 2017"
testicules = "\"Kiniamaro: Dude calme tes testicules\" - Maro-Kun 2019"
